In [ ]:
%autosave 30

Autosaving every 30 seconds

# Pandas

In [ ]:
# 1. Understand the business problem
# 2. Import data/Connect data (SQL)
# 3. import python packages
# 4. Data understanding
# 5. Data Cleaning/Preprocessing
# 6. EDA
# 7. Data cleaning
# 8. KPI's (Feature engineering)
# 9. Data Analysis

In [ ]:
import numpy as np
import pandas as pd

# 1.Data Importing

In [ ]:
df =  pd.read_excel("/content/Bank_data.xlsx")   # read_sql, read_csv etc

# 2.Understanding Data

In [ ]:
df.head()   # first 5 observations

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df.head(10)  # first 10

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
6,59,admin.,married,professional.course,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
7,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
8,24,technician,single,professional.course,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
9,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df.tail()  # last 5

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
41183,73,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,yes,no,cellular,nov,fri,...,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,no,cellular,nov,fri,...,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,yes,no,cellular,nov,fri,...,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [ ]:
df.sample() # random

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
27983,49,admin.,married,basic.6y,no,yes,no,cellular,apr,wed,...,2,999,1,failure,-1.8,93.075,-47.1,1.498,5099.1,yes

In [ ]:
df.shape

(41188, 21)

In [ ]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [ ]:
df.info()  # both shape and columns together and a lot more together

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 41188 entries, 0 to 41187
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             41188 non-null  int64
 1   job             41188 non-null  object
 2   marital         41188 non-null  object
 3   education       41188 non-null  object
 4   default         41188 non-null  object
 5   housing         41188 non-null  object
 6   loan            41188 non-null  object
 7   contact         41188 non-null  object
 8   month           41188 non-null  object
 9   day_of_week     41188 non-null  object
 10  duration        41188 non-null  int64
 11  campaign        41188 non-null  int64
 12  pdays           41188 non-null  int64
 13  previous        41188 non-null  int64
 14  poutcome        41188 non-null  object
 15  emp.var.rate    41188 non-null  float64
 16  cons.price.idx  41188 non-null  float64
 17  cons.conf.idx   41188 non-null  float64
 18  euribor3m       41188 non-null  float64
 19  nr.employed     41188 non-null  float64
 20  y               41188 non-null  object
dtypes: float64(5), int64(5), object(11)
memory usage: 6.6+ MB

In [ ]:
df.isnull().sum()  # missing records in the columns

age               0
job               0
marital           0
education         0
default           0
housing           0
loan              0
contact           0
month             0
day_of_week       0
duration          0
campaign          0
pdays             0
previous          0
poutcome          0
emp.var.rate      0
cons.price.idx    0
cons.conf.idx     0
euribor3m         0
nr.employed       0
y                 0
dtype: int64

In [ ]:
df.describe()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
count,41188.00000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000,41188.000000
mean,40.02406,258.285010,2.567593,962.475454,0.172963,0.081886,93.575664,-40.502600,3.621291,5167.035911
std,10.42125,259.279249,2.770014,186.910907,0.494901,1.570960,0.578840,4.628198,1.734447,72.251528
min,17.00000,0.000000,1.000000,0.000000,0.000000,-3.400000,92.201000,-50.800000,0.634000,4963.600000
25%,32.00000,102.000000,1.000000,999.000000,0.000000,-1.800000,93.075000,-42.700000,1.344000,5099.100000
50%,38.00000,180.000000,2.000000,999.000000,0.000000,1.100000,93.749000,-41.800000,4.857000,5191.000000
75%,47.00000,319.000000,3.000000,999.000000,0.000000,1.400000,93.994000,-36.400000,4.961000,5228.100000
max,98.00000,4918.000000,56.000000,999.000000,7.000000,1.400000,94.767000,-26.900000,5.045000,5228.100000

In [ ]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
age,41188.0,40.024060,10.421250,17.000,32.000,38.000,47.000,98.000
duration,41188.0,258.285010,259.279249,0.000,102.000,180.000,319.000,4918.000
campaign,41188.0,2.567593,2.770014,1.000,1.000,2.000,3.000,56.000
pdays,41188.0,962.475454,186.910907,0.000,999.000,999.000,999.000,999.000
previous,41188.0,0.172963,0.494901,0.000,0.000,0.000,0.000,7.000
emp.var.rate,41188.0,0.081886,1.570960,-3.400,-1.800,1.100,1.400,1.400
cons.price.idx,41188.0,93.575664,0.578840,92.201,93.075,93.749,93.994,94.767
cons.conf.idx,41188.0,-40.502600,4.628198,-50.800,-42.700,-41.800,-36.400,-26.900
euribor3m,41188.0,3.621291,1.734447,0.634,1.344,4.857,4.961,5.045
nr.employed,41188.0,5167.035911,72.251528,4963.600,5099.100,5191.000,5228.100,5228.100

In [ ]:
# std < mean = Good data
# diff between min & 25%, 25% & 50%, 50% & 75% and 75% & max should be same, otherwise there are outliers

In [ ]:
df.describe(include = 'object').T  # for text based analysis.

             count unique                top   freq
job          41188     12             admin.  10422
marital      41188      4            married  24928
education    41188      8  university.degree  12168
default      41188      3                 no  32588
housing      41188      3                yes  21576
loan         41188      3                 no  33950
contact      41188      2           cellular  26144
month        41188     10                may  13769
day_of_week  41188      5                thu   8623
poutcome     41188      3        nonexistent  35563
y            41188      2                 no  36548

In [ ]:
# less number of options are better for text based info. eg: gender is better than city.

In [ ]:
# for number based info, more data points are useful

# 3.Data Manipulation - data subset, data indexing

# Level 1

##Subset

Data Types

In [ ]:
df1 = df.select_dtypes(include = 'number')  # only numeric data

In [ ]:
df1.head()

,age,duration,campaign,pdays,previous,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed
0,56,261,1,999,0,1.1,93.994,-36.4,4.857,5191.0
1,57,149,1,999,0,1.1,93.994,-36.4,4.857,5191.0
2,37,226,1,999,0,1.1,93.994,-36.4,4.857,5191.0
3,40,151,1,999,0,1.1,93.994,-36.4,4.857,5191.0
4,56,307,1,999,0,1.1,93.994,-36.4,4.857,5191.0

In [ ]:
df2 = df.select_dtypes(include = 'object') # only text data

In [ ]:
df2.head()

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,y
0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,nonexistent,no
1,services,married,high.school,unknown,no,no,telephone,may,mon,nonexistent,no
2,services,married,high.school,no,yes,no,telephone,may,mon,nonexistent,no
3,admin.,married,basic.6y,no,no,no,telephone,may,mon,nonexistent,no
4,services,married,high.school,no,no,yes,telephone,may,mon,nonexistent,no

In [ ]:
df3 = df.select_dtypes(include = ["float", "object"]) # select multiple data types

In [ ]:
df3.head()

,job,marital,education,default,housing,loan,contact,month,day_of_week,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,services,married,high.school,unknown,no,no,telephone,may,mon,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,services,married,high.school,no,yes,no,telephone,may,mon,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,admin.,married,basic.6y,no,no,no,telephone,may,mon,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,services,married,high.school,no,no,yes,telephone,may,mon,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

Condition

In [ ]:
df4 = df[df['marital'] == "married"]

In [ ]:
df4.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df5 = df[(df['marital'] == "married") & (df['age'] > 45)]  # and in python, & in pandas.

In [ ]:
df5.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
6,59,admin.,married,professional.course,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
15,54,retired,married,basic.9y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df6 = df[df['education'].isin(["high.school","basic.4y"])]

In [ ]:
df6.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
9,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df7 = df[df['job'].isin(["services","housemaid"])]

In [ ]:
df7.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df8 = df[df['age'].between(40,50)]  # 40 & 50 are inclusive

In [ ]:
df8.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
7,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
10,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
17,46,blue-collar,married,basic.6y,unknown,yes,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
#str.contains -- for partial names

df9 = df[df['education'].str.contains('basic')]
df9.head()

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
13,57,housemaid,divorced,basic.4y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
14,35,blue-collar,married,basic.6y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
#query

df.query("age > 50 & job == 'housemaid'")

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
13,57,housemaid,divorced,basic.4y,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
211,55,housemaid,divorced,university.degree,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
307,57,housemaid,divorced,basic.4y,no,yes,yes,telephone,may,mon,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
458,54,housemaid,married,basic.4y,no,no,no,telephone,may,tue,...,2,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
40478,67,housemaid,divorced,professional.course,no,no,no,cellular,aug,thu,...,1,6,2,success,-1.7,94.027,-38.3,0.899,4991.6,yes
40716,82,housemaid,married,basic.4y,no,no,no,telephone,sep,tue,...,3,3,2,success,-1.1,94.199,-37.5,0.877,4963.6,yes
40938,51,housemaid,married,basic.4y,no,no,no,cellular,oct,tue,...,2,999,2,failure,-1.1,94.601,-49.5,0.982,4963.6,no
40999,61,housemaid,married,basic.4y,no,yes,no,telephone,oct,wed,...,2,999,2,failure,-1.1,94.601,-49.5,1.016,4963.6,no
41153,67,housemaid,divorced,professional.course,no,yes,no,cellular,nov,mon,...,2,5,5,success,-1.1,94.767,-50.8,1.039,4963.6,yes

In [ ]:
# highest age

#nlargest
#nsmallest

In [ ]:
df.nlargest(2,'age')

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
38452,98,retired,married,basic.4y,unknown,yes,no,cellular,oct,fri,...,1,2,2,success,-3.4,92.431,-26.9,0.73,5017.5,yes
38455,98,retired,married,basic.4y,unknown,yes,no,cellular,oct,fri,...,2,999,0,nonexistent,-3.4,92.431,-26.9,0.73,5017.5,yes

In [ ]:
df.nsmallest(2,'age')

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
37140,17,student,single,unknown,no,yes,no,cellular,aug,wed,...,3,4,2,success,-2.9,92.201,-31.4,0.884,5076.2,no
37539,17,student,single,basic.9y,no,yes,no,cellular,aug,fri,...,2,999,2,failure,-2.9,92.201,-31.4,0.869,5076.2,no

Columns & Rows

In [ ]:
df.head(2)

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df.columns

Index(['age', 'job', 'marital', 'education', 'default', 'housing', 'loan',
       'contact', 'month', 'day_of_week', 'duration', 'campaign', 'pdays',
       'previous', 'poutcome', 'emp.var.rate', 'cons.price.idx',
       'cons.conf.idx', 'euribor3m', 'nr.employed', 'y'],
      dtype='object')

In [ ]:
df10 = df[["marital","education","job"]]

In [ ]:
df10.head()

   marital    education        job
0  married     basic.4y  housemaid
1  married  high.school   services
2  married  high.school   services
3  married     basic.6y     admin.
4  married  high.school   services

loc & iloc

In [ ]:
# loc - location (column name)
#iloc - integer location (column postion/index)

In [ ]:
df.loc[:,["marital","education","job"]]

       marital            education          job
0      married             basic.4y    housemaid
1      married          high.school     services
2      married          high.school     services
3      married             basic.6y       admin.
4      married          high.school     services
...        ...                  ...          ...
41183  married  professional.course      retired
41184  married  professional.course  blue-collar
41185  married    university.degree      retired
41186  married  professional.course   technician
41187  married  professional.course      retired

[41188 rows x 3 columns]

In [ ]:
df.iloc[:,[1,4,8]]

               job  default month
0        housemaid       no   may
1         services  unknown   may
2         services       no   may
3           admin.       no   may
4         services       no   may
...            ...      ...   ...
41183      retired       no   nov
41184  blue-collar       no   nov
41185      retired       no   nov
41186   technician       no   nov
41187      retired       no   nov

[41188 rows x 3 columns]

In [ ]:
df.loc[0:200,["marital","education","job"]]

     marital    education          job
0    married     basic.4y    housemaid
1    married  high.school     services
2    married  high.school     services
3    married     basic.6y       admin.
4    married  high.school     services
..       ...          ...          ...
196  married  high.school       admin.
197   single     basic.9y  blue-collar
198  married     basic.9y       admin.
199  married     basic.6y  blue-collar
200  married  high.school     services

[201 rows x 3 columns]

In [ ]:
df.iloc[0:200,[1,4,8]]

             job  default month
0      housemaid       no   may
1       services  unknown   may
2       services       no   may
3         admin.       no   may
4       services       no   may
..           ...      ...   ...
195  blue-collar       no   may
196       admin.  unknown   may
197  blue-collar  unknown   may
198       admin.  unknown   may
199  blue-collar       no   may

[200 rows x 3 columns]

In [ ]:
df.loc[[1,5,10],:]

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
10,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df.loc[0:10,:]

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
6,59,admin.,married,professional.course,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
7,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
8,24,technician,single,professional.course,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
9,25,services,single,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
10,41,blue-collar,married,unknown,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df.loc[ df['age'] > 50    , ["age","marital","education","job"]            ]

       age   marital            education        job
0       56   married             basic.4y  housemaid
1       57   married          high.school   services
4       56   married          high.school   services
6       59   married  professional.course     admin.
13      57  divorced             basic.4y  housemaid
...    ...       ...                  ...        ...
41178   62   married    university.degree    retired
41179   64  divorced  professional.course    retired
41183   73   married  professional.course    retired
41185   56   married    university.degree    retired
41187   74   married  professional.course    retired

[7180 rows x 4 columns]

# Level 2

In [ ]:
# .assign

In [ ]:
#.drop   axis 1 -> columns, axis 0 -> rows
df.drop('age', axis = 1)  # will only effect the view but not the real data

,job,marital,education,default,housing,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,housemaid,married,basic.4y,no,no,no,telephone,may,mon,261,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,services,married,high.school,unknown,no,no,telephone,may,mon,149,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,services,married,high.school,no,yes,no,telephone,may,mon,226,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,admin.,married,basic.6y,no,no,no,telephone,may,mon,151,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,services,married,high.school,no,no,yes,telephone,may,mon,307,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,retired,married,professional.course,no,yes,no,cellular,nov,fri,334,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,blue-collar,married,professional.course,no,no,no,cellular,nov,fri,383,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,retired,married,university.degree,no,yes,no,cellular,nov,fri,189,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,technician,married,professional.course,no,no,no,cellular,nov,fri,442,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,retired,married,professional.course,no,yes,no,cellular,nov,fri,239,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

In [ ]:
df.head() # age row comes back

,age,job,marital,education,default,housing,loan,contact,month,day_of_week,...,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,yes,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,no,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,no,yes,telephone,may,mon,...,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df.drop('housing', axis = 1, inplace = True)  # removes completely

In [ ]:
df.head()

,age,job,marital,education,default,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,telephone,may,mon,261,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,telephone,may,mon,149,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
2,37,services,married,high.school,no,no,telephone,may,mon,226,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
3,40,admin.,married,basic.6y,no,no,telephone,may,mon,151,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,yes,telephone,may,mon,307,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no

In [ ]:
df.drop([2,3],axis =0)

,age,job,marital,education,default,loan,contact,month,day_of_week,duration,campaign,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y
0,56,housemaid,married,basic.4y,no,no,telephone,may,mon,261,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
1,57,services,married,high.school,unknown,no,telephone,may,mon,149,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
4,56,services,married,high.school,no,yes,telephone,may,mon,307,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
5,45,services,married,basic.9y,unknown,no,telephone,may,mon,198,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
6,59,admin.,married,professional.course,no,no,telephone,may,mon,139,1,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,no,cellular,nov,fri,334,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41184,46,blue-collar,married,professional.course,no,no,cellular,nov,fri,383,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41185,56,retired,married,university.degree,no,no,cellular,nov,fri,189,2,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no
41186,44,technician,married,professional.course,no,no,cellular,nov,fri,442,1,999,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes
41187,74,retired,married,professional.course,no,no,cellular,nov,fri,239,3,999,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no

Binning Data

In [ ]:
# convert numerical to categorical data

#pd.cut

Manual Binning

In [ ]:
df['AC'] = pd.cut(df['age'], bins = [0,35,50,100], labels = ['young','middle','old'])

In [ ]:
df.head()

,age,job,marital,education,default,loan,contact,month,day_of_week,duration,...,pdays,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,AC
0,56,housemaid,married,basic.4y,no,no,telephone,may,mon,261,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old
1,57,services,married,high.school,unknown,no,telephone,may,mon,149,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old
2,37,services,married,high.school,no,no,telephone,may,mon,226,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,middle
3,40,admin.,married,basic.6y,no,no,telephone,may,mon,151,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,middle
4,56,services,married,high.school,no,yes,telephone,may,mon,307,...,999,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old

Equidistance Binning

In [ ]:
df['EB - AC'] = pd.cut(df['age'], 3 , labels = ['Young','middle','old'])  # column, no of cuts, label name

In [ ]:
df.head()

,age,job,marital,education,default,loan,contact,month,day_of_week,duration,...,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,AC,EB - AC
0,56,housemaid,married,basic.4y,no,no,telephone,may,mon,261,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old,middle
1,57,services,married,high.school,unknown,no,telephone,may,mon,149,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old,middle
2,37,services,married,high.school,no,no,telephone,may,mon,226,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,middle,Young
3,40,admin.,married,basic.6y,no,no,telephone,may,mon,151,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,middle,Young
4,56,services,married,high.school,no,yes,telephone,may,mon,307,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old,middle

Rename

In [ ]:
df.rename(columns = {"day_of_week" : "week"})

,age,job,marital,education,default,loan,contact,month,week,duration,...,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,AC,EB - AC
0,56,housemaid,married,basic.4y,no,no,telephone,may,mon,261,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old,middle
1,57,services,married,high.school,unknown,no,telephone,may,mon,149,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old,middle
2,37,services,married,high.school,no,no,telephone,may,mon,226,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,middle,Young
3,40,admin.,married,basic.6y,no,no,telephone,may,mon,151,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,middle,Young
4,56,services,married,high.school,no,yes,telephone,may,mon,307,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old,middle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,73,retired,married,professional.course,no,no,cellular,nov,fri,334,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes,old,old
41184,46,blue-collar,married,professional.course,no,no,cellular,nov,fri,383,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no,middle,middle
41185,56,retired,married,university.degree,no,no,cellular,nov,fri,189,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no,old,middle
41186,44,technician,married,professional.course,no,no,cellular,nov,fri,442,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes,middle,Young
41187,74,retired,married,professional.course,no,no,cellular,nov,fri,239,...,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no,old,old

Sort

In [ ]:
df.sort_values(by = 'age', ascending = False)

,age,job,marital,education,default,loan,contact,month,day_of_week,duration,...,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,AC,EB - AC
38455,98,retired,married,basic.4y,unknown,no,cellular,oct,fri,272,...,0,nonexistent,-3.4,92.431,-26.9,0.730,5017.5,yes,old,old
38452,98,retired,married,basic.4y,unknown,no,cellular,oct,fri,476,...,2,success,-3.4,92.431,-26.9,0.730,5017.5,yes,old,old
27826,95,retired,divorced,basic.6y,no,no,cellular,mar,thu,85,...,0,nonexistent,-1.8,92.843,-50.0,1.650,5099.1,no,old,old
38921,94,retired,married,basic.9y,no,no,cellular,nov,wed,134,...,1,failure,-3.4,92.649,-30.1,0.716,5017.5,no,old,old
39655,92,retired,married,unknown,no,no,cellular,may,thu,271,...,2,success,-1.8,93.876,-40.0,0.683,5008.7,no,old,old
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37558,17,student,single,basic.9y,no,no,cellular,aug,fri,92,...,2,success,-2.9,92.201,-31.4,0.869,5076.2,no,young,Young
37140,17,student,single,unknown,no,no,cellular,aug,wed,432,...,2,success,-2.9,92.201,-31.4,0.884,5076.2,no,young,Young
38274,17,student,single,unknown,no,yes,cellular,oct,tue,896,...,2,success,-3.4,92.431,-26.9,0.742,5017.5,yes,young,Young
37579,17,student,single,basic.9y,no,unknown,cellular,aug,fri,498,...,1,failure,-2.9,92.201,-31.4,0.869,5076.2,yes,young,Young
37539,17,student,single,basic.9y,no,no,cellular,aug,fri,182,...,2,failure,-2.9,92.201,-31.4,0.869,5076.2,no,young,Young

In [ ]:
df.sort_values(by = ['age','job'], ascending = [False, True])

,age,job,marital,education,default,loan,contact,month,day_of_week,duration,...,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,AC,EB - AC
38452,98,retired,married,basic.4y,unknown,no,cellular,oct,fri,476,...,2,success,-3.4,92.431,-26.9,0.730,5017.5,yes,old,old
38455,98,retired,married,basic.4y,unknown,no,cellular,oct,fri,272,...,0,nonexistent,-3.4,92.431,-26.9,0.730,5017.5,yes,old,old
27826,95,retired,divorced,basic.6y,no,no,cellular,mar,thu,85,...,0,nonexistent,-1.8,92.843,-50.0,1.650,5099.1,no,old,old
38921,94,retired,married,basic.9y,no,no,cellular,nov,wed,134,...,1,failure,-3.4,92.649,-30.1,0.716,5017.5,no,old,old
39655,92,retired,married,unknown,no,no,cellular,may,thu,271,...,2,success,-1.8,93.876,-40.0,0.683,5008.7,no,old,old
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
37140,17,student,single,unknown,no,no,cellular,aug,wed,432,...,2,success,-2.9,92.201,-31.4,0.884,5076.2,no,young,Young
37539,17,student,single,basic.9y,no,no,cellular,aug,fri,182,...,2,failure,-2.9,92.201,-31.4,0.869,5076.2,no,young,Young
37558,17,student,single,basic.9y,no,no,cellular,aug,fri,92,...,2,success,-2.9,92.201,-31.4,0.869,5076.2,no,young,Young
37579,17,student,single,basic.9y,no,unknown,cellular,aug,fri,498,...,1,failure,-2.9,92.201,-31.4,0.869,5076.2,yes,young,Young
38274,17,student,single,unknown,no,yes,cellular,oct,tue,896,...,2,success,-3.4,92.431,-26.9,0.742,5017.5,yes,young,Young

Type Converters

In [ ]:
# .apply(pd.to_numeric)
# .astye(int64)

Set & Reset Index

In [ ]:
df.set_index('job')

,age,marital,education,default,loan,contact,month,day_of_week,duration,campaign,...,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,AC,EB - AC
job,,,,,,,,,,,,,,,,,,,,,
housemaid,56,married,basic.4y,no,no,telephone,may,mon,261,1,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old,middle
services,57,married,high.school,unknown,no,telephone,may,mon,149,1,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old,middle
services,37,married,high.school,no,no,telephone,may,mon,226,1,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,middle,Young
admin.,40,married,basic.6y,no,no,telephone,may,mon,151,1,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,middle,Young
services,56,married,high.school,no,yes,telephone,may,mon,307,1,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old,middle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
retired,73,married,professional.course,no,no,cellular,nov,fri,334,1,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes,old,old
blue-collar,46,married,professional.course,no,no,cellular,nov,fri,383,1,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no,middle,middle
retired,56,married,university.degree,no,no,cellular,nov,fri,189,2,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no,old,middle
technician,44,married,professional.course,no,no,cellular,nov,fri,442,1,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes,middle,Young
retired,74,married,professional.course,no,no,cellular,nov,fri,239,3,...,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no,old,old

In [ ]:
df.reset_index()

,index,age,job,marital,education,default,loan,contact,month,day_of_week,...,previous,poutcome,emp.var.rate,cons.price.idx,cons.conf.idx,euribor3m,nr.employed,y,AC,EB - AC
0,0,56,housemaid,married,basic.4y,no,no,telephone,may,mon,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old,middle
1,1,57,services,married,high.school,unknown,no,telephone,may,mon,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old,middle
2,2,37,services,married,high.school,no,no,telephone,may,mon,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,middle,Young
3,3,40,admin.,married,basic.6y,no,no,telephone,may,mon,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,middle,Young
4,4,56,services,married,high.school,no,yes,telephone,may,mon,...,0,nonexistent,1.1,93.994,-36.4,4.857,5191.0,no,old,middle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,41183,73,retired,married,professional.course,no,no,cellular,nov,fri,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes,old,old
41184,41184,46,blue-collar,married,professional.course,no,no,cellular,nov,fri,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no,middle,middle
41185,41185,56,retired,married,university.degree,no,no,cellular,nov,fri,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,no,old,middle
41186,41186,44,technician,married,professional.course,no,no,cellular,nov,fri,...,0,nonexistent,-1.1,94.767,-50.8,1.028,4963.6,yes,middle,Young
41187,41187,74,retired,married,professional.course,no,no,cellular,nov,fri,...,1,failure,-1.1,94.767,-50.8,1.028,4963.6,no,old,old